/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMyPostsRouteImport } from './routes/app.my-posts'
import { Route as AppInterviewExperiencesRouteImport } from './routes/app.interview-experiences'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBookmarksRouteImport } from './routes/app.bookmarks'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMyPostsRoute = AppMyPostsRouteImport.update({
  id: '/my-posts',
  path: '/my-posts',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewExperiencesRoute = AppInterviewExperiencesRouteImport.update({
  id: '/interview-experiences',
  path: '/interview-experiences',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/interview-experiences': typeof AppInterviewExperiencesRoute
  '/app/my-posts': typeof AppMyPostsRoute
  '/app/profile': typeof AppProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/interview-experiences': typeof AppInterviewExperiencesRoute
  '/app/my-posts': typeof AppMyPostsRoute
  '/app/profile': typeof AppProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/interview-experiences': typeof AppInterviewExperiencesRoute
  '/app/my-posts': typeof AppMyPostsRoute
  '/app/profile': typeof AppProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/bookmarks'
    | '/app/dashboard'
    | '/app/interview-experiences'
    | '/app/my-posts'
    | '/app/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/bookmarks'
    | '/app/dashboard'
    | '/app/interview-experiences'
    | '/app/my-posts'
    | '/app/profile'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/bookmarks'
    | '/app/dashboard'
    | '/app/interview-experiences'
    | '/app/my-posts'
    | '/app/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-posts': {
      id: '/app/my-posts'
      path: '/my-posts'
      fullPath: '/app/my-posts'
      preLoaderRoute: typeof AppMyPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interview-experiences': {
      id: '/app/interview-experiences'
      path: '/interview-experiences'
      fullPath: '/app/interview-experiences'
      preLoaderRoute: typeof AppInterviewExperiencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookmarks': {
      id: '/app/bookmarks'
      path: '/bookmarks'
      fullPath: '/app/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInterviewExperiencesRoute: typeof AppInterviewExperiencesRoute
  AppMyPostsRoute: typeof AppMyPostsRoute
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookmarksRoute: AppBookmarksRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInterviewExperiencesRoute: AppInterviewExperiencesRoute,
  AppMyPostsRoute: AppMyPostsRoute,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
